index:
   path: /
   controller: App\Controller\ArticleController::homepage

second:
  path: /second
  controller: App\Controller\ArticleController::nextpage

lucky_number:
    path: /number
    controller: App\Controller\ArticleController::number